"""add vehicle and mission models

Revision ID: 7e8540cb7847
Revises:
Create Date: 2026-05-27 18:20:16.131005

"""
from alembic import op
import sqlalchemy as sa


revision = '7e8540cb7847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('current_zone', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
