"""update telemetry constraints and indexes

Revision ID: 801ff1f94784
Revises: abb76334fdbc
Create Date: 2026-05-28 09:44:26.503427

"""
from alembic import op
import sqlalchemy as sa


revision = '801ff1f94784'
down_revision = 'abb76334fdbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_telemetry_vehicle_timestamp', 'telemetry_events', ['vehicle_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_telemetry_zone_entered', 'telemetry_events', ['zone_entered', 'timestamp'], unique=False, postgresql_where=sa.text('zone_entered IS NOT NULL'))
    op.create_check_constraint('ck_battery_range', 'telemetry_events', 'battery_pct >= 0 AND battery_pct <= 100')
    op.create_check_constraint('ck_speed_nonneg', 'telemetry_events', 'speed_mps >= 0')
    op.create_check_constraint('ck_status_valid', 'telemetry_events', "status IN ('idle', 'moving', 'charging', 'fault')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_status_valid', 'telemetry_events', type_='check')
    op.drop_constraint('ck_speed_nonneg', 'telemetry_events', type_='check')
    op.drop_constraint('ck_battery_range', 'telemetry_events', type_='check')
    op.drop_index('ix_telemetry_zone_entered', table_name='telemetry_events', postgresql_where=sa.text('zone_entered IS NOT NULL'))
    op.drop_index('ix_telemetry_vehicle_timestamp', table_name='telemetry_events')
    # ### end Alembic commands ###
