"""add telemetry events model

Revision ID: abb76334fdbc
Revises: 7e8540cb7847
Create Date: 2026-05-27 19:44:26.793793

"""
from alembic import op
import sqlalchemy as sa


revision = 'abb76334fdbc'
down_revision = '7e8540cb7847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_codes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('zone_entered', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_events')
    # ### end Alembic commands ###
