"""add maintenance records and mission lifecycle fields

Revision ID: cc0a2f0f96fc
Revises: d2c26a9edfc0
Create Date: 2026-05-29 20:07:51.308918

"""
from alembic import op
import sqlalchemy as sa


revision = 'cc0a2f0f96fc'
down_revision = 'd2c26a9edfc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('triggering_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['triggering_event_id'], ['telemetry_events.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    op.add_column('missions', sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('missions', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('missions', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_missions_vehicle_id'), 'missions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_vehicle_id'), table_name='missions')
    op.drop_column('missions', 'cancel_reason')
    op.drop_column('missions', 'cancelled_at')
    op.drop_column('missions', 'started_at')
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
