"""add zone counters model

Revision ID: d2c26a9edfc0
Revises: 801ff1f94784
Create Date: 2026-05-28 17:54:16.403556

"""
from alembic import op
import sqlalchemy as sa


revision = 'd2c26a9edfc0'
down_revision = '801ff1f94784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_counters',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('entry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_counters')
    # ### end Alembic commands ###
